### ISSUE TITLE
cucumber crash with wire protocol while output format is html

### ISSUE THREAD

**Issue by canmor** [cucumber/cucumber-ruby-wire#56]
Here's exception stack
```
➜ cucumber -f html -o out.html

WARNING: # built-in usage of the wire protocol is deprecated and will be removed after version 8.0.0. See https://github.com/cucumber/cucumber-ruby/blob/main/UPGRADING.md#upgrading-to-710 for more info.
(Called from /Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/runtime.rb:77:in `run!')
undefined method `id' for #<Cucumber::Wire::StepDefinition:0x00007fa31abba548> (NoMethodError)
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/query/step_definitions_by_test_step.rb:34:in `on_step_activated'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/configuration.rb:34:in `notify'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:53:in `result'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:29:in `map'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/compiler.rb:31:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/gherkin/parser.rb:46:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core.rb:35:in `parse'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core.rb:24:in `compile'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/runtime.rb:83:in `run!'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/bin/cucumber:9:in `<top (required)>'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `load'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `<main>'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

After some investigation, I found that the code throw exception here is requiring method `id` of `StepDefinition`:

https://github.com/cucumber/cucumber-ruby/blob/47c8e2d7c97beae8541c895a43f9ccb96324f0f1/lib/cucumber/formatter/query/step_definitions_by_test_step.rb#L34

But `StepDefinition` in wire library did not define reader for `id`:

https://github.com/cucumber/cucumber-ruby-wire/blob/6564cf5c85dc1ea6e67de03e9c8f13fe12376e9c/lib/cucumber/wire/step_definition.rb#L6

After define a `id` attr_reader in code above, it works.

Please investigate which library should be fix?

**Comment by aurelien-reeves** [comment]
Thanks for the report.
Indeed, it seems the `id` attribute is missing from `StepDefinition`

**Comment by aurelien-reeves** [comment]
I took a deeper look.
It looks like the wire protocol is actually not compatible with formatters based on cucumber-messages.
When attempting to add a reproducible example and fixing that specific issue, more issues was raised :(

I'll submit a PR

**Comment by canmor** [comment]
Hi @aurelien-reeves ,
Thx for your work on this issue, the problem related to `id attribute is missing from StepDefinition` is indeed fixed.
But as you mentioned previously: 
> wire protocol is actually not compatible with formatters based on cucumber-messages 

New issue raised after this fix:

```shell
$ cucumber -f html -o out.html

WARNING: # built-in usage of the wire protocol is deprecated and will be removed after version 8.0.0. See https://github.com/cucumber/cucumber-ruby/blob/main/UPGRADING.md#upgrading-to-710 for more info.
(Called from /Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/runtime.rb:77:in `run!')
undefined method `parameter_type' for #<Cucumber::Wire::StepArgument:0x00007f96ad7da6e0> (NoMethodError)
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:132:in `block in step_match_arguments'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:129:in `map'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:129:in `step_match_arguments'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:120:in `step_match_arguments_lists'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:108:in `test_step_to_message'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:94:in `block in on_test_case_ready'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:94:in `map'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/formatter/message_builder.rb:94:in `on_test_case_ready'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/configuration.rb:34:in `notify'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/broadcast_test_case_ready_event.rb:7:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/apply_around_hooks.rb:10:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/apply_after_hooks.rb:7:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/apply_before_hooks.rb:7:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/apply_after_step_hooks.rb:10:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-wire-6.2.1/lib/cucumber/wire/add_hooks_filter.rb:8:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/case.rb:28:in `describe_to'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/compiler.rb:31:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core/gherkin/parser.rb:46:in `done'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core.rb:35:in `parse'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-core-10.1.0/lib/cucumber/core.rb:24:in `compile'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/runtime.rb:83:in `run!'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
/Users/canmor/.rvm/gems/ruby-2.6.3/gems/cucumber-7.1.0/bin/cucumber:9:in `<top (required)>'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `load'
/Users/canmor/.rvm/gems/ruby-2.6.3/bin/cucumber:23:in `<main>'

```

Code here is requesting for `parameter_type` from Cucumber::Wire::StepArgument:

https://github.com/cucumber/cucumber-ruby/blob/e8b3bd310f641261ab38c70a10bfa876b7deee66/lib/cucumber/formatter/message_builder.rb#L132

I'd tried to add a test case base on the case you added on your pr, this issue cloud be reproduced, but I'm not sure how to fix this, because as far as I known about wire protocol (I can't find any document for wire protocol), I guess wire protocol could not provide such information for us to new a Cucumber::Messages::ParameterType for this.

Could you offer some further helps? Much appreciate.

**Comment by canmor** [comment]
Hi @aurelien-reeves,
I'm sorry for my extremely late reply, I hope you are doing well during the past year.

May be I didn't make it clear in my previous comment, there's no need to setup a dedicated reproducible example, just change the test case you'd created by adding any argument, will make this happened.

I have changed your test case data to:

```
       | request                                              | response                                                                           |
      | ["step_matches",{"name_to_match":"we're all wired"}] | ["success",[{"id":"1", "args":[{"pos": 11, "val": "wired"}], "source":"MyApp.MyClass:123", "regexp":"we're all (.*)"}]] |
       | ["begin_scenario"]                                   | ["success"]                                                                        |
      | ["invoke",{"id":"1","args":["wired"]}]               | ["success"]                                                                        |
       | ["end_scenario"]                                     | ["success"]                                                                        |
```

And get simply workaround for this, see PR #65

Thanks for you help on this, If you get any suggestion or question, we can disscuss on that PR.

**Comment by luke-hill** [comment]
Hi @canmor 

This actually needed fixing properly downstream. I've had a go at this, can you test with the bugfix branch.

NB: This is based off the cucumber-ruby 9.x series.

The branch for cucumber-ruby is https://github.com/cucumber/cucumber-ruby/tree/bugfix/make_parameter_type_optional_in_envelope

If this works I'll merge it in in the new year
